const cfg=window.APP_CONFIG||{};const sb=(cfg.supabaseUrl&&cfg.supabaseAnonKey)?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;let state={};
const $=s=>document.querySelector(s),money=n=>`฿${Number(n||0).toLocaleString()}`;function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}
async function api(action,payload={}){const {data}=await sb.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('กรุณาเข้าสู่ระบบจากหน้าร้านก่อน');const r=await fetch(`${cfg.supabaseUrl}/functions/v1/admin-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,apikey:cfg.supabaseAnonKey},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Server error');return j}
async function boot(){try{if(!sb)throw new Error('ยังไม่ได้ตั้งค่า app-config.js');const me=await api('me');if(!me.is_admin)throw new Error('บัญชีนี้ไม่มีสิทธิ์เข้าหน้าหลังบ้าน');$('#adminIdentity').textContent=`Owner • ${me.email}`;$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');await load()}catch(e){$('#gateText').textContent=e.message;$('#backBtn').classList.remove('hidden')}}
async function load(){try{state=await api('dashboard');render()}catch(e){toast(e.message)}}
function render(){const s=state.stats||{};$('#statIncome').textContent=money(s.approved_income);$('#statCredits').textContent=money(s.total_credit_balance);$('#statPending').textContent=s.pending_topups||0;$('#statUsers').textContent=s.users||0;$('#pendingChip').textContent=`${s.pending_topups||0} pending`;renderChart();renderRecent();renderTopups();renderUsers();renderLedger()}
function renderChart(){const data=state.daily_income||[];const max=Math.max(1,...data.map(x=>Number(x.total)));$('#incomeChart').innerHTML=data.map(x=>`<div class="bar" style="--h:${Math.max(5,Number(x.total)/max*100)}%" data-label="${x.day}: ${money(x.total)}"></div>`).join('')||'<p style="color:var(--muted)">ยังไม่มีข้อมูล</p>'}
function renderRecent(){const arr=(state.topups||[]).slice(0,6);$('#recentList').innerHTML=arr.map(x=>`<div style="display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid var(--line)"><div><b>${x.email||'ผู้ใช้'}</b><small style="display:block;color:var(--muted)">${new Date(x.created_at).toLocaleString('th-TH')}</small></div><div style="text-align:right"><b>${money(x.amount)}</b><small class="status ${x.status}" style="display:block">${x.status}</small></div></div>`).join('')||'<p style="color:var(--muted)">ยังไม่มีรายการ</p>'}
function renderTopups(){const arr=state.topups||[];$('#topupRows').innerHTML=arr.map(x=>`<tr><td>${x.slip_url?`<img class="thumb" src="${x.slip_url}" onclick='openSlip(${JSON.stringify(x)})'>`:'-'}</td><td>${x.email||'-'}<small>${x.user_id.slice(0,8)}</small></td><td><b>${money(x.amount)}</b></td><td>${x.transfer_reference||'-'}</td><td>${new Date(x.created_at).toLocaleString('th-TH')}</td><td><span class="status ${x.status}">${x.status}</span></td><td>${x.status==='pending'?`<button class="btn good" onclick="review('${x.id}','approve')">อนุมัติ</button> <button class="btn bad" onclick="review('${x.id}','reject')">ปฏิเสธ</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="7">ไม่มีรายการ</td></tr>'}
function renderUsers(){const arr=state.users||[];$('#userRows').innerHTML=arr.map(x=>`<tr><td>${x.email||'-'}<small>${x.id}</small></td><td><b>${money(x.credit_balance)}</b></td><td>${new Date(x.created_at).toLocaleDateString('th-TH')}</td><td><button class="btn" onclick="selectUser('${x.id}')">เลือก</button></td></tr>`).join('')||'<tr><td colspan="4">ไม่มีผู้ใช้</td></tr>'}
function renderLedger(){const arr=state.ledger||[];$('#ledgerRows').innerHTML=arr.map(x=>`<tr><td><span class="status ${x.amount>=0?'approved':'rejected'}">${x.amount>=0?'รายรับ':'รายจ่าย'}</span></td><td><b>${x.amount>=0?'+':''}${money(x.amount)}</b></td><td>${x.note||'-'}</td><td>${new Date(x.created_at).toLocaleString('th-TH')}</td></tr>`).join('')||'<tr><td colspan="4">ไม่มีรายการ</td></tr>'}
async function review(id,mode){const note=prompt(mode==='approve'?'หมายเหตุการอนุมัติ (ไม่บังคับ)':'เหตุผลที่ปฏิเสธ')||'';try{await api(mode==='approve'?'approve_topup':'reject_topup',{request_id:id,note});toast(mode==='approve'?'เพิ่มเครดิตแล้ว':'ปฏิเสธรายการแล้ว');await load()}catch(e){toast(e.message)}}
function selectUser(id){$('#adjustUserId').value=id;document.querySelector('[data-section="users"]').click()}async function adjust(){try{await api('adjust_credit',{user_id:$('#adjustUserId').value.trim(),amount:Number($('#adjustAmount').value),note:$('#adjustNote').value.trim()});toast('ปรับเครดิตเรียบร้อย');$('#adjustAmount').value='';$('#adjustNote').value='';await load()}catch(e){toast(e.message)}}async function addLedger(){try{await api('add_ledger',{amount:Number($('#ledgerAmount').value),note:$('#ledgerNote').value.trim()});toast('เพิ่มรายการบัญชีแล้ว');$('#ledgerAmount').value='';$('#ledgerNote').value='';await load()}catch(e){toast(e.message)}}
window.openSlip=x=>{$('#modalSlip').src=x.slip_url;$('#modalInfo').textContent=`${x.email} • ${money(x.amount)} • ${x.transfer_reference||''}`;$('#slipModal').classList.add('open')};window.closeSlip=()=>$('#slipModal').classList.remove('open');window.review=review;window.selectUser=selectUser;
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===b.dataset.section));$('#pageTitle').textContent=b.textContent.trim()});$('#refreshBtn').onclick=load;$('#adjustBtn').onclick=adjust;$('#ledgerBtn').onclick=addLedger;$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href='index.html'};boot();
