import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const auth=createClient(url,anon,{global:{headers:{Authorization:req.headers.get("Authorization")||""}}});const db=createClient(url,key,{auth:{persistSession:false}});const {data:{user}}=await auth.auth.getUser();if(!user)return out({error:"unauthorized"},401);const {data:role}=await db.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();const b=await req.json().catch(()=>({}));if(b.action==="me")return out({is_admin:!!role,email:user.email});if(!role)return out({error:"forbidden"},403);
if(b.action==="approve_topup"){const {data,error}=await db.rpc("admin_approve_topup",{p_request_id:b.request_id,p_admin_id:user.id,p_note:String(b.note||"")});if(error)throw error;return out({ok:true,new_balance:data});}
if(b.action==="reject_topup"){const {data,error}=await db.from("topup_requests").update({status:"rejected",admin_note:String(b.note||""),reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq("id",b.request_id).eq("status","pending").select("id").maybeSingle();if(error)throw error;return data?out({ok:true}):out({error:"already_reviewed"},409);}
if(b.action==="adjust_credit"){const {data,error}=await db.rpc("admin_adjust_credit",{p_user_id:b.user_id,p_amount:Number(b.amount),p_admin_id:user.id,p_note:String(b.note||"")});if(error)throw error;return out({ok:true,new_balance:data});}
if(b.action==="add_ledger"){const {error}=await db.from("admin_ledger").insert({amount:Number(b.amount),note:String(b.note||""),created_by:user.id});if(error)throw error;return out({ok:true});}
if(b.action!=="dashboard")return out({error:"unknown_action"},400);
const [t,p,l,a]=await Promise.all([db.from("topup_requests").select("*").order("created_at",{ascending:false}).limit(200),db.from("profiles").select("id,credit_balance,created_at").order("created_at",{ascending:false}).limit(500),db.from("admin_ledger").select("*").order("created_at",{ascending:false}).limit(300),db.auth.admin.listUsers({page:1,perPage:1000})]);if(t.error||p.error||l.error||a.error)throw(t.error||p.error||l.error||a.error);const m=new Map((a.data.users||[]).map((x:any)=>[x.id,x.email]));const topups=[];for(const x of t.data||[]){const {data:s}=await db.storage.from("payment-slips").createSignedUrl(x.slip_path,900);topups.push({...x,email:m.get(x.user_id)||null,slip_url:s?.signedUrl||""})}const users=(p.data||[]).map((x:any)=>({...x,email:m.get(x.id)||null}));const approved=(t.data||[]).filter((x:any)=>x.status==="approved");const daily_income=[];for(let i=13;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);daily_income.push({day:key.slice(5),total:approved.filter((x:any)=>x.reviewed_at?.slice(0,10)===key).reduce((n:number,x:any)=>n+x.amount,0)})}return out({stats:{approved_income:approved.reduce((n:number,x:any)=>n+x.amount,0),total_credit_balance:(p.data||[]).reduce((n:number,x:any)=>n+Number(x.credit_balance||0),0),pending_topups:(t.data||[]).filter((x:any)=>x.status==="pending").length,users:(a.data.users||[]).length},daily_income,topups,users,ledger:l.data||[]});}catch(e){return out({error:e instanceof Error?e.message:String(e)},500)}});
